"""add parsed column to resumes

Revision ID: 584cf4cec8ea
Revises: dc305eaa5d15
Create Date: 2026-08-03 22:05:04.116924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584cf4cec8ea'
down_revision: Union[str, Sequence[str], None] = 'dc305eaa5d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed')
    # ### end Alembic commands ###
