"""add parsed columns to jobs

Revision ID: d969628add65
Revises: d611439499d2
Create Date: 2026-08-04 21:54:38.257795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd969628add65'
down_revision: Union[str, Sequence[str], None] = 'd611439499d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parsed', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('parsed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'parsed_data')
    op.drop_column('jobs', 'parsed')
    # ### end Alembic commands ###
